### PR TITLE
Add get_typename implementations for boost::interprocess containers

### PR DESCRIPTION
**Pull request by theoreticalbts**

### CODE REVIEW

**Comment by theoreticalbts** [comment]
Made a dummy commit on Steem to bump FC to this version on the `bip-container-typename` branch, let's wait to merge until CI shows green on that branch (you can see CI report for a branch [in the branches view](https://github.com/steemit/steem/branches) )

**Comment by theoreticalbts** [comment]
Oops, looks like `flat_map` needs to be included after all

**Comment by theoreticalbts** [comment]
CI works now.

**Comment by theoreticalbts** [comment]
Revised it, will update CI branch in a minute.

**Comment by mvandeberg** [comment]
@theoreticalbts This is still needed?

**Comment by theoreticalbts** [comment]
Yes.

**Pull request merged**
