### PR TITLE
Fix fc get typename

### PR DESCRIPTION
**Pull request by mkochanowicz**

### CODE REVIEW

**Comment by mvandeberg** [comment]
Why is this a PR against #22?

**Comment by mkochanowicz** [comment]
To be honest - I've just tried to minimize no of other commits. What is the proper way? Choose `develop` as base?

**Comment by mvandeberg** [comment]
The branch should be based on and merged back to master.

The branch `22-websocket-api-newlines` has not been merged. And we only want steem to use `fc/master` commits.

**Comment by mvandeberg** [comment]
I'm not entirely sure what you did in your commit history. It is probably easiest just to make a new branch based on master and cherry pick the relevant commit on to that branch.

In the meantime, @theoreticalbts should make a PR for #22.

**Comment by mkochanowicz** [comment]
These changes already commited into `master` (6 days ago), so I close this PR.

**Comment by mvandeberg** [comment]
We don't have the same enforced branch protection on fc, but please do not merge to `master` without having either @theoreticalbts or myself review it.

**Comment by mkochanowicz** [comment]
OK, I'll remember it for the future. Simply I didn't know that.

**Pull request closed without merging**
